title: ZIoT Systems
logo: /assets/img/logoZZ.png
description:
show_downloads: true
google_analytics: G-JWQ5MWZHPH
theme: jekyll-theme-minimal
pages:  https://ziot-systems.github.io/

plugins:
  - jekyll-sitemap